# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Arman Yessymkanov - A frontend developer
email: arman.yessymkanov@gmail.com
description: A frontend developer based in Astana. Ready to collaborate. Contact me if I can help you anyhow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ayessymkanov.kz" # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown
